name: Load Testing Workflow
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run Load Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run k6 local test
        uses: k6io/action@v0.4.0
        with:
          filename: k6_practices/performanceTesting_11_08_2025/test.js
