name: Load Testing Workflow
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run Load Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Recommended to use a modern version

      - name: Setup K6 üõ†Ô∏è
        uses: grafana/setup-k6-action@v1 # Step 1: Install k6

      - name: Run k6 local test
        uses: grafana/run-k6-action@v1 # Step 2: Run the test
        with:
          # Use the correct path from your repo root
          path: k6_practices/performanceTesting_11_08_2025/test.js
